# Generated by Django 5.2.10 on 2026-01-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_view', 'Can view member'), ('can_create', 'Can create member'), ('can_edit', 'Can edit member'), ('can_delete', 'Can delete member')],
            },
        ),
    ]
